@echo off
echo Cleaning up old virtual environment...
if exist venv rmdir /s /q venv
echo Creating virtual environment...
py -3.12 -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Streamlit app...
streamlit run app.py
